version: '3.8'
services:
  jupyter:
    image: autor0503/my-jupyter-image:latest
    command: ["start-notebook.sh", "--NotebookApp.token=${JUPYTER_TOKEN}"]  # Usar valor de variable de entorno JUPYTER_TOKEN como contraseña
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}  # Variable de entorno para la contraseña
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work  # Montar en el directorio actual

  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8889:8888"
